### ISSUE TITLE
Timestamps in log output

### ISSUE THREAD

**Issue by hhoffstaette** [nondeterministic/mailfilter#2]
Not a bug but an RFE. I recently started to use mailfilter again and noticed that log messages were kind of hard to read/debug since they didn't have time stamps; so I added them, just like for the upcoming fetchmail-6.5 release.
Output now looks like this:
```
Jan 22 13:58:39 mailfilter: 0.8.7 querying holger@xxx@yyy on Sat Jan 22 13:58:39 2022.
Jan 22 13:58:39 mailfilter: Examining 0 message(s).
``` 
Or when filtering:
```
Jan 21 23:32:26 mailfilter: Deny: "SmartCam" <smartcam@beamflattoll.co>: The Tiny, Discreet, Extra small size Video Recorder!, Fri, 21 Jan 2022 17:08:17 -0500 ["^From:.*\.co>" matches "From: "SmartCam" <smartcam@beamflattoll.co>"].
```
Does this seem like a useful improvement? My branch commit is [here](https://github.com/hhoffstaette/mailfilter/commit/4c240337ae596873dff1bbf4ffcb9bc486bb4fae), let me know what you think and I'll create a PR.

**Comment by nondeterministic** [comment]
That's wonderful, many thanks. You may have noticed, I have a new release in the pipeline anyways, and this one could fit right in. I'm a bit busy right now, but will try to integrate your work. If problems or questions arise in the process, I shall get back to you. This is just to let you know that I've seen it and to inform you of some recent work (you'll need to check out the latest dev branch, if you want to know what's new; basically only a bug fix).

**Comment by nondeterministic** [comment]
I have added it. I may, before I release, also remove the double timestamps in the "<date> mailfilter: ... querying ... on <date>" - unless you feel motivated to fix it. But even if not, it's no big deal, I think, to leave it as is. Thanks again and sorry for having been somewhat slow.
